[package]
name = "r0t0blocks"
version = "0.1.0"
authors = ["r0t0r-r0t0r"]
edition = "2018"

[dependencies]
fastrand = "1.4.1"
enum_dispatch = "0.3.6"

engine = { version = "0.1.0", path = "../engine", package = "engine" }
